<?php

declare(strict_types=1);

// Explanations of form sections, used only by the generated data-model document
// (`php artisan docs:datamodel`).
//
// This is a different kind of text than information_blocks.php: that one tells
// someone filling in a form how to answer, while these notes tell an outside
// reader what the system can record.
//
// The keys are referenced through #[DocNote] on the schema method.

return [
    // The document's own vocabulary: column headings and the description of
    // each kind of input field.
    'column_field' => 'Field',
    'column_kind' => 'Kind of input',
    'column_help' => 'Explanation',

    'kind' => [
        'text' => 'Text',
        'textarea' => 'Free text',
        'boolean' => 'Yes/no',
        'date' => 'Date',
        'choice' => 'Choice',
        'multiple_choice' => 'Multiple choice',
        'free_tags' => 'Multiple choice (free)',
        'relation' => 'Link',
        'list' => 'List',
        'file' => 'File',
    ],

    'generated_header' => [
        'line_1' => 'This file is generated by `just docs-datamodel`.',
        'line_2' => 'Changes made here will be lost.',
        'line_3' => 'The field tables come from the Filament forms; change those',
        'line_4' => '(labels and helper texts live in resources/lang/). The surrounding',
        'line_5' => 'text lives in docs/prose/.',
    ],

    'options_prefix' => 'Choose from: :options.',

    'avg_responsible_processing_record' => [
        'stakeholders' => 'The most detailed part of the record. For each category of data '
            . 'subjects it captures which ordinary, special and sensitive data are processed, '
            . 'and for each item the collection purpose, the retention period and the source.',
    ],
];
