<?php

declare(strict_types=1);

namespace App\Console\Commands;

use App\Models\Organisation;
use App\Models\User;
use Illuminate\Console\Command;

use function implode;
use function json_encode;
use function sprintf;
use function str_replace;

use const JSON_PRETTY_PRINT;
use const JSON_THROW_ON_ERROR;
use const JSON_UNESCAPED_SLASHES;
use const JSON_UNESCAPED_UNICODE;

/**
 * Exports the tenants and memberships this application holds, so they can be
 * provisioned into the Pratique proxy.
 *
 * READ-ONLY, deliberately. It writes a plan to stdout and changes nothing — not
 * here and not in the proxy. Running it against production is safe, which is the
 * point: the risky half (the `pratique admin` calls) is a separate step that a
 * human runs against a plan they have read.
 *
 * What does NOT come across, and cannot:
 *
 *  - **Credentials.** Pratique has no password concept, and this application has
 *    had no password column since 2024 — logins are magic-link + TOTP. So there
 *    is nothing to migrate, but every user re-bootstraps with an emailed code on
 *    first login, and their TOTP enrolment does not survive.
 *  - **Global roles.** `functional-manager` is cross-tenant and has no UI here;
 *    it stays in this application's own tables (see the migration plan, §3.2) and
 *    is therefore excluded from the per-organisation role lists below.
 */
class PratiqueExportProvisioning extends Command
{
    protected $signature = 'pratique:export-provisioning
        {--format=json : json for a machine-readable plan, sh for a runnable script}';
    protected $description = 'Export organisations and memberships for provisioning into Pratique';

    public function handle(): int
    {
        $organisations = Organisation::query()->get()->sortBy('slug');

        /** @var array<int, array{slug: string, name: string, members: array<int, array{email: string, name: string, roles: array<int, string>}>}> $plan */
        $plan = [];

        foreach ($organisations as $organisation) {
            $plan[] = [
                'slug' => $organisation->slug,
                'name' => $organisation->name,
                'members' => $this->members($organisation),
            ];
        }

        $this->line($this->option('format') === 'sh'
            ? $this->script($plan)
            : json_encode($plan, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR));

        return self::SUCCESS;
    }

    /**
     * The members of one organisation, with the roles they hold *there*.
     *
     * A member with no roles is still exported: membership and authorisation are
     * separate facts, and someone who can reach a tenant but do nothing in it is
     * a state this application already supports.
     *
     * @return array<int, array{email: string, name: string, roles: array<int, string>}>
     */
    private function members(Organisation $organisation): array
    {
        $members = [];

        $users = $organisation->users()->get()->sortBy('email');

        foreach ($users as $user) {
            $members[] = [
                'email' => $user->email,
                'name' => $user->name,
                'roles' => $this->roles($user, $organisation),
            ];
        }

        return $members;
    }

    /**
     * Roles held in this organisation only. Global roles are excluded on purpose
     * — they are not the proxy's to know about.
     *
     * @return array<int, string>
     */
    private function roles(User $user, Organisation $organisation): array
    {
        return $user->organisationRoles()
            ->where('organisation_id', $organisation->id)
            ->get()
            ->map(static fn ($organisationRole): string => $organisationRole->role->value)
            ->unique()
            ->values()
            ->all();
    }

    /**
     * A runnable provisioning script.
     *
     * Every step is guarded rather than assumed, because the `pratique admin`
     * commands are create-only: `create-org` fails on a duplicate slug, and
     * `add-member` inserts a membership row that is UNIQUE per (user, org). A
     * re-run without guards therefore fails partway and leaves the operator
     * unsure how much of it took effect. Guarded, the script is safe to run
     * again after fixing whatever stopped it.
     *
     * @param array<int, array{slug: string, name: string, members: array<int, array{email: string, name: string, roles: array<int, string>}>}> $plan
     */
    private function script(array $plan): string
    {
        $lines = [
            '#!/usr/bin/env bash',
            '#',
            '# Provisions this application\'s tenants and memberships into Pratique.',
            '# Generated by `artisan pratique:export-provisioning --format=sh`.',
            '#',
            '# Idempotent: every step probes first, so a re-run after a failure',
            '# resumes rather than erroring on what already exists.',
            '#',
            '# Users are created implicitly by add-member. Nobody receives mail from',
            '# this script; each user gets an emailed code on their first login.',
            '',
            'set -euo pipefail',
            '',
            'PRATIQUE="${PRATIQUE:-pratique}"',
            '',
            '# Prints an org id, creating the org only when the slug is absent.',
            '# get-org exits 4 for "not found", 1 for a real failure — so a broken',
            '# connection is never mistaken for an absent organisation.',
            'ensure_org() {',
            '  local slug="$1" name="$2" id rc',
            '  set +e',
            '  id="$("$PRATIQUE" admin get-org -slug "$slug" 2>/dev/null)"',
            '  rc=$?',
            '  set -e',
            '  case "$rc" in',
            '    0) printf \'%s\' "$id" ;;',
            '    4) "$PRATIQUE" admin create-org -slug "$slug" -name "$name" ;;',
            '    *) echo "get-org failed for $slug (rc=$rc)" >&2; return 1 ;;',
            '  esac',
            '}',
            '',
            '# Adds a member unless that email already has a membership in the org.',
            'ensure_member() {',
            '  local org="$1" email="$2" roles="$3"',
            '  if "$PRATIQUE" admin list-members -org "$org" | cut -f1 | grep -Fxq "$email"; then',
            '    echo "  = $email (already a member)"',
            '    return 0',
            '  fi',
            '  "$PRATIQUE" admin add-member -org "$org" -email "$email" -roles "$roles" >/dev/null',
            '  echo "  + $email [$roles]"',
            '}',
            '',
        ];

        foreach ($plan as $organisation) {
            $lines[] = sprintf('echo %s', self::quote(sprintf('== %s (%s)', $organisation['name'], $organisation['slug'])));
            $lines[] = sprintf(
                'ORG_ID="$(ensure_org %s %s)"',
                self::quote($organisation['slug']),
                self::quote($organisation['name']),
            );

            foreach ($organisation['members'] as $member) {
                // Pass roles explicitly even when there are none. The -roles flag
                // DEFAULTS to "member", so omitting it would grant a role this
                // application never gave; an empty string parses to an empty set,
                // which is the accurate translation of "a member with no roles".
                $roles = implode(',', $member['roles']);

                $lines[] = sprintf(
                    'ensure_member "$ORG_ID" %s %s',
                    self::quote($member['email']),
                    self::quote($roles),
                );
            }

            $lines[] = '';
        }

        return implode("\n", $lines);
    }

    /** Single-quote a value for the shell, escaping any embedded quote. */
    private static function quote(string $value): string
    {
        return "'" . str_replace("'", "'\\''", $value) . "'";
    }
}
